In [9]:
import csv
import pandas as pd

In [10]:
test = pd.read_csv('../corpora/eng/cv-valid-test.csv', 
        parse_dates=False,
        engine="python",
        encoding="utf-8",
        error_bad_lines=False,
        quotechar='"',
        quoting=csv.QUOTE_NONE,)
test["text"].value_counts().to_frame().reset_index().describe()

              text
count  2362.000000
mean      1.691363
std       1.267989
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max      12.000000

In [11]:
train = pd.read_csv('../corpora/eng/cv-valid-train.csv', 
        parse_dates=False,
        engine="python",
        encoding="utf-8",
        error_bad_lines=False,
        quotechar='"',
        quoting=csv.QUOTE_NONE,)
train["text"].value_counts().to_frame().reset_index().describe()

              text
count  6994.000000
mean     27.991993
std      38.371750
min       1.000000
25%       9.000000
50%      16.000000
75%      29.000000
max     265.000000

In [12]:
dev = pd.read_csv('../corpora/eng/cv-valid-dev.csv', 
        parse_dates=False,
        engine="python",
        encoding="utf-8",
        error_bad_lines=False,
        quotechar='"',
        quoting=csv.QUOTE_NONE,)
dev["text"].value_counts().to_frame().reset_index().describe()

              text
count  2410.000000
mean      1.691286
std       1.237694
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max      12.000000

In [24]:
train.loc[ lambda df: (df.up_votes + df.down_votes > 1) & (df.up_votes > df.down_votes), : ]

,filename,text,up_votes,down_votes,age,gender,accent,duration
4,cv-valid-train/sample-000004.mp3,if you start your emails with greetings let me...,3,2,NaN,NaN,NaN,NaN
6,cv-valid-train/sample-000006.mp3,night fell and an assortment of fighting men a...,3,0,NaN,NaN,NaN,NaN
7,cv-valid-train/sample-000007.mp3,i heard a faint movement under my feet,2,1,NaN,NaN,NaN,NaN
8,cv-valid-train/sample-000008.mp3,put jackie right on the staff,3,0,seventies,male,us,NaN
11,cv-valid-train/sample-000011.mp3,if you have to wait until the war is over then...,3,0,NaN,NaN,NaN,NaN
12,cv-valid-train/sample-000012.mp3,my wife pointed out to me the brightness of th...,2,0,NaN,NaN,NaN,NaN
15,cv-valid-train/sample-000015.mp3,i couldnt stop staring at it,2,0,NaN,NaN,NaN,NaN
17,cv-valid-train/sample-000017.mp3,but he decided to take a chance,3,0,NaN,NaN,NaN,NaN
20,cv-valid-train/sample-000020.mp3,it was faintly marked with transverse stripes ...,5,1,thirties,male,england,NaN
21,cv-valid-train/sample-000021.mp3,i have no information about troops or about th...,5,0,NaN,NaN,NaN,NaN
22,cv-valid-train/sample-000022.mp3,fill this place with a sandstorm so strong tha...,3,0,NaN,NaN,NaN,NaN
23,cv-valid-train/sample-000023.mp3,i had seen all that it would presently bring me,5,0,thirties,male,us,NaN
24,cv-valid-train/sample-000024.mp3,i make my living forecasting the future for pe...,3,0,NaN,NaN,NaN,NaN
26,cv-valid-train/sample-000026.mp3,two years ago right here on this spot i had a ...,4,0,twenties,female,australia,NaN
27,cv-valid-train/sample-000027.mp3,don't let them see that you're afraid the alch...,3,0,twenties,male,australia,NaN
30,cv-valid-train/sample-000030.mp3,coming home a party of tourists passed us sing...,3,0,NaN,NaN,NaN,NaN
31,cv-valid-train/sample-000031.mp3,before guns were invented armies had to throw ...,4,0,NaN,NaN,NaN,NaN
32,cv-valid-train/sample-000032.mp3,before guns were invented armies had to throw ...,4,0,NaN,NaN,NaN,NaN
36,cv-valid-train/sample-000036.mp3,ask the owner of that stall how much the sword...,2,1,twenties,male,australia,NaN
37,cv-valid-train/sample-000037.mp3,it was dropping off in flakes and raining down...,4,0,NaN,NaN,NaN,NaN
38,cv-valid-train/sample-000038.mp3,maybe that's why they give up on it so early too,3,1,NaN,NaN,NaN,NaN
39,cv-valid-train/sample-000039.mp3,a large piece suddenly came off and fell with ...,3,1,teens,female,canada,NaN
44,cv-valid-train/sample-000044.mp3,they were people of the desert and clamored to...,2,0,thirties,male,england,NaN
45,cv-valid-train/sample-000045.mp3,my seven year resume gap is marked not drugs,2,0,NaN,NaN,NaN,NaN
47,cv-valid-train/sample-000047.mp3,most of them were staring quietly at the big t...,3,0,sixties,male,us,NaN
48,cv-valid-train/sample-000048.mp3,you wanna take this outside,2,0,NaN,NaN,NaN,NaN
49,cv-valid-train/sample-000049.mp3,so how will we name all these hurricanes,2,1,fourties,male,australia,NaN
51,cv-valid-train/sample-000051.mp3,so the boy was disappointed he decided that he...,2,0,thirties,female,us,NaN
52,cv-valid-train/sample-000052.mp3,how do you mean,2,0,NaN,NaN,NaN,NaN
53,cv-valid-train/sample-000053.mp3,don't you know that girl's very sick,2,0,fourties,male,england,NaN
...,...,...,...,...,...,...,...,...
195726,cv-valid-train/sample-195726.mp3,they formed heaps that are visible a mile and ...,8,0,NaN,NaN,NaN,NaN
195727,cv-valid-train/sample-195727.mp3,all they think about is food and water,3,0,NaN,NaN,NaN,NaN
195730,cv-valid-train/sample-195730.mp3,a boy came running towards me,3,0,NaN,NaN,NaN,NaN
195732,cv-valid-train/sample-195732.mp3,air was either entering or escaping at the rim...,3,0,NaN,NaN,NaN,NaN
195735,cv-valid-train/sample-195735.mp3,now leave us alone said the boy to the young arab,2,0,NaN,NaN,NaN,NaN
195737,cv-valid-train/sample-195737.mp3,the thief wasn't there and the owner brought h...,2,0,NaN,NaN,NaN,NaN
195738,cv-valid-train/sample-195738.mp3,they are so used to me that they know my sched...,3,0,NaN,NaN,NaN,NaN
195741,cv-valid-train/sample-195741.mp3,i want to stay at the oasis the boy answered,3,0,fifties,male,australia,NaN
195742,cv-valid-train/sample-195742.mp3,all that time the martians must have been gett...,6,0,fifties,female,us,NaN
195744,cv-valid-train/sample-195744.mp3,the boy went to look for the englishman,4,0,NaN,NaN,NaN,NaN
195745,cv-valid-train/sample-195745.mp3,all the joy he had seen that morning had sudde...,3,0,NaN,NaN,NaN,NaN
195748,cv-valid-train/sample-195748.mp3,i gotta figure some way out of this thing,2,0,thirties,male,us,NaN
195749,cv-valid-train/sample-195749.mp3,so they think she left it with you,2,0,thirties,male,us,NaN
195750,cv-valid-train/sample-195750.mp3,in his youth my dad was a hooligan,2,0,thirties,female,england,NaN
195751,cv-valid-train/sample-195751.mp3,i need you to be spontaneous he asked me out t...,3,0,twenties,male,us,NaN
195753,cv-valid-train/sample-195753.mp3,two more months passed and the shelf brought m...,3,0,NaN,NaN,NaN,NaN
195755,cv-valid-train/sample-195755.mp3,he just got a new kite for his birthday,4,1,NaN,NaN,NaN,NaN
195756,cv-valid-train/sample-195756.mp3,then suddenly they kneel and die,2,0,thirties,male,us,NaN
195757,cv-valid-train/sample-195757.mp3,some of those who saw its flight say it travel...,2,0,twenties,male,NaN,NaN
195758,cv-valid-train/sample-195758.mp3,ogilvy told him everything that he had seen,3,1,twenties,female,england,NaN
195759,cv-valid-train/sample-195759.mp3,the snake fought frantically making hissing so...,2,0,NaN,NaN,NaN,NaN
195763,cv-valid-train/sample-195763.mp3,it seemed as if what the old king had called b...,3,0,NaN,NaN,NaN,NaN
195764,cv-valid-train/sample-195764.mp3,i'll work for you he said,3,1,NaN,NaN,NaN,NaN
195765,cv-valid-train/sample-195765.mp3,it was harassment pure and simple,2,0,twenties,female,australia,NaN
195767,cv-valid-train/sample-195767.mp3,down below in the darkness were hundreds of pe...,3,0,thirties,female,us,NaN
195768,cv-valid-train/sample-195768.mp3,i have been waiting for you here at this oasis...,2,0,NaN,NaN,NaN,NaN
195769,cv-valid-train/sample-195769.mp3,the burning fire had been extinguished,2,0,NaN,NaN,NaN,NaN
195770,cv-valid-train/sample-195770.mp3,he heard a muffled grating sound and saw the b...,4,0,twenties,male,england,NaN
195774,cv-valid-train/sample-195774.mp3,the phone rang while she was awake,2,0,twenties,male,us,NaN
195775,cv-valid-train/sample-195775.mp3,among these people were a couple of cyclists a...,4,1,NaN,NaN,NaN,NaN